version: '3.7'

# linked services 
services:
    app: 
        build:
            context: ./
        environment: 
            XDEBUG_CONFIG: remote_host=${XDEBUG_REMOTE_HOST:-host.docker.internal}
    web:
        # install nginx
        image: nginx:latest
        ports: 
            # expose ports
            - "80:80"
        volumes:
            # mount existing folders into : docker folders ( no space before/after colomn)
            - ../work:/web
            # easy access to logs
            - ./logs/nginx:/var/logs/nginx
            # mount nginx config in order to make site available
            - ./conf/nginx/test.conf:/etc/nginx/conf.d/test.conf
            - ./conf/nginx/kine.conf:/etc/nginx/conf.d/kine.conf
            - ./conf/nginx/remote.conf:/etc/nginx/conf.d/remote.conf
        
    php:
        # required version of php
        image: php:7.1-fpm
        volumes:
            # mount existing folders into : docker folders ( no space before/after colomn)
            - ../work:/web
            # setup some config
            - ./logs/php:/var/logs/xdebug
            - ./conf/php/php-fpm.conf:/usr/local/etc/php-fpm.d/log.conf
            - ./conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
